### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by ntdesmond**
Allow to install the library in a quick way (after the git repo is cloned):
```sh
cd SrdPy; pip install -r requirements.txt; pip install .
```

### CODE REVIEW

**Comment by RumblingTurtle** [comment]
You can do that already, setup.py has it all but without proper meshcat install. Thanks for the idea

**Comment by ntdesmond** [comment]
Oh, so that's why it installs everything but meshcat unless doing a separate `pip install -r requirements.txt`
Edited the original comment.

**Comment by RumblingTurtle** [comment]
So you have issues installation through pip install .?

**Comment by ntdesmond** [comment]
> 
> 
> So you have issues installation through pip install .?

Due to `meshcat` not being included in `setup.py`, yes. But again, this only requires a separate call to `pip` beforehand.

It could be also investigated on how to include `meshcat` directly to `setup.py`, though.

**Pull request merged**
